# Generated by Django 5.2.15 on 2026-06-16 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=250)),
                ('años_experiencia_guia', models.PositiveIntegerField()),
                ('idiomas_hablados', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Guía de museo',
                'verbose_name_plural': 'Guías de museo',
            },
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('ciudad', models.CharField(max_length=150)),
                ('año_fundacion', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Museo',
                'verbose_name_plural': 'Museos',
            },
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=250)),
                ('duracion_meses', models.PositiveIntegerField()),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tematica', models.CharField(max_length=200)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibiciones', to='institucion.guiamuseo')),
            ],
            options={
                'verbose_name': 'Exhibición',
                'verbose_name_plural': 'Exhibiciones',
            },
        ),
        migrations.AddField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guias', to='institucion.museo'),
        ),
    ]
