# Generated by Django 5.2.15 on 2026-06-16 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibicion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guiamuseo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='museo',
            options={},
        ),
    ]
